@startuml Server_Class_Diagram
package "Server" {
    node "Server_Manager" {
        node "Lobby" {
            node "Game Logic" {
            }
        }
        [Server_Manager_Obj] -left- port
        [Server_Manager_Obj] -down-> [HTTP Server]
        [Server_Manager_Obj] -down-> [Websocket Server]
        [Server_Manager_Obj] -right-> Lobby


    }
    
    [Websocket Server] --> Lobby : handle
    [HTTP Server] --> Lobby : handle
}
@enduml